[package]
name = "alpha_points"
version = "0.0.1"
# edition = "2024.beta" # Optional: Specify Move edition if needed

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" } # Adjust 'rev' as needed for devnet/testnet/mainnet or specific commits

[addresses]
# You might define named addresses here later, e.g., for deployment or admin
# alpha_points = "0x0" # Placeholder, will be assigned on deployment